// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BrowserLinkInspector
{
				static class Vsix
				{
								public const string Id = "9b651fbe-f7a1-43ff-b7ec-288709f2cb26";
								public const string Name = "Browser Link Inspector 2019";
								public const string Description = @"Adds inspect and debug mode directly in the browsers";
								public const string Language = "en-US";
								public const string Version = "0.5";
								public const string Author = "Mads Kristensen";
								public const string Tags = "browser link";
				}
}
