// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BrowserLinkInspector
{
    static class Vsix
    {
        public const string Id = "bc4780ab-de6e-4999-bebf-51390e1b75ef";
        public const string Name = "Browser Link Inspector 2017";
        public const string Description = @"Adds inspect and debug mode directly in the browsers";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "browser link";
    }
}
